required:
  - '@id'
  - '@type'
  - id
type: object
properties:
  '@type':
    type: string
    description: Resource type.
  '@id':
    type: string
    description: >-
      Used to specify the URI for the resource. Can be used by clients to
      navigate back to that specific resource.
  '@links':
    type: object
    properties: {}
    description: Links to related resources.
  id:
    type: string
    description: Resource unique identifier.
  environment_id:
    type: string
    description: Environment ID
  primary_cert:
    type: string
    description: Primary certificate. Not returned for records in collection.
  intermediate_cert:
    type: string
    description: Intermediate certificate. Not returned for records in collection
  expiration:
    type: string
    description: Expiration date
    format: date-time
  status:
    type: string
    description: Status
  generated:
    type: boolean
    description: Generated
  serial:
    type: string
    description: Serial
  common_name:
    type: string
    description: Common name
  alternative_names:
    type: array
    description: Alternative names
  activation_error:
    type: string
    description: Activation error
  created_at:
    type: string
    description: Created at
    format: date-time
  updated_at:
    type: string
    description: Updated at
    format: date-time
description: Config_V1_Entities_TlsCert model
