required:
  - '@id'
  - '@type'
type: object
properties:
  '@type':
    type: string
    description: Resource type.
  '@id':
    type: string
    description: >-
      Used to specify the URI for the resource. Can be used by clients to
      navigate back to that specific resource.
  '@links':
    type: object
    properties: {}
    description: Links to related resources.
  logs:
    $ref: ./Config_V1_Entities_Deployment_LogLine.yaml
description: Config_V1_Entities_Deployment_Logs model
