name: Publish to docs-pages
on:
  push:
    branches:
      - master
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Pull docs from S3 bucket
        run: |
          mkdir s3
          aws s3 sync s3://layer0-docs ./s3  --delete
      - name: Sync guides to latest version path
        run: |
          cd s3
          VERSION=$(tail -n 1 versions.csv)
          cp -r ../guides ${VERSION}
          cp -r ../guides current
          cp ../guides/guides.json ${VERSION}/guides.json
          cp ../guides/guides.json current/guides.json
      - name: Deploy docs to S3 bucket
        run: |
          cd s3
          aws s3 sync . s3://layer0-docs --delete
      - name: Crawl Docs
        run: |
          docker run \
          -e APPLICATION_ID=${{ secrets.ALGOLIA_APP_ID }} \
          -e API_KEY=${{ secrets.ALGOLIA_API_KEY }} \
          -e CONFIG="$(cat ./docs.config.json | jq -r tostring)" \
          algolia/docsearch-scraper
