name: Publish docs to s3
on:
  push:
    branches:
      - test-docs
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm ci
      - uses: actions/checkout@v2
        with:
          repository: layer0-docs/layer0-docs-pages
          token: ${{ secrets.MOOVWEB_GITHUB_TOKEN }}
          path: pages-repo
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Push guides to GitHub Pages repo
        run: |
          cd pages-repo
          VERSION=$(tail -n 1 versions.csv)
          cp -r ../guides ${VERSION}
          cp -r ../guides current
          cp ../guides/guides.json ${VERSION}/guides.json
          cp ../guides/guides.json current/guides.json
      - name: Deploy static site to S3 bucket
        run: |
          cd pages-repo
          aws s3 rm s3://layer0-docs --recursive
          aws s3 sync . s3://layer0-docs --delete
      # - name: Crawl Docs
      #   run: |
      #     docker run \
      #     -e APPLICATION_ID=${{ secrets.ALGOLIA_APP_ID }} \
      #     -e API_KEY=${{ secrets.ALGOLIA_API_KEY }} \
      #     -e CONFIG="$(cat ./docs.config.json | jq -r tostring)" \
      #     algolia/docsearch-scraper
