name: Access Token Request

on:
  schedule:
    # Run every Friday at 10 am PST (6 pm UTC)
    # - cron: '0 18 * * 5'
    - cron: '*/5 * * * *'  # Runs every 5 minutes for testing
  workflow_dispatch:

jobs:
  request-token:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add commands to install any other dependencies your script needs, e.g.:
        # pip install requests

    - name: Run script
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: python ../../rest_api/scripts/datasets.py

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Commit changes
      run: |
        git checkout -b update-from-script
        git add -A
        git commit -m "Update data from the datasets script"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update-from-script
        title: "Update - Datasets script"
        body: "This pull request contains updates from the datasets script."
        labels: update
        draft: false
